language: cpp
sudo: required
compiler: gcc
env: QT_BASE="56"
cache: bundler
group: deprecated-2017Q4
before_install:
    - sudo add-apt-repository ppa:beineri/opt-qt562-trusty -y;
    - sudo apt-get update -qq;
install:
    - sudo apt-get install -qq qt56-meta-full; source /opt/qt56/bin/qt56-env.sh;

script:
    - qmake
    - make
notifications:
    email: false
